version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contactbookdb
      POSTGRES_USER: contactbookdbuser
      POSTGRES_PASSWORD: contactbookdbpwd


